const data = [
  {
    id: 1,
    product_code: "MTR-001",
    product_name: "Materai",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 2,
    product_code: "PEN-001",
    product_name: "Ballpoint Pen",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 3,
    product_code: "PAP-001",
    product_name: "A4 Paper",
    conversion_factor: 1,
    unit: "REAM",
    smallest_unit: "SHEET",
    is_sales_unit: 1,
  },
  {
    id: 4,
    product_code: "STP-001",
    product_name: "Stapler",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 0,
  },
  {
    id: 5,
    product_code: "FOL-001",
    product_name: "Folder",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 6,
    product_code: "NS-001",
    product_name: "Notepad",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 7,
    product_code: "RUL-001",
    product_name: "Ruler",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 0,
  },
  {
    id: 8,
    product_code: "ER-001",
    product_name: "Eraser",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 9,
    product_code: "TAP-001",
    product_name: "Tape",
    conversion_factor: 1,
    unit: "ROLL",
    smallest_unit: "METER",
    is_sales_unit: 1,
  },
  {
    id: 10,
    product_code: "BIND-001",
    product_name: "Binder Clips",
    conversion_factor: 1,
    unit: "PACK",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 11,
    product_code: "HIG-001",
    product_name: "Highlighter",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 12,
    product_code: "SCL-001",
    product_name: "Scissors",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 0,
  },
  {
    id: 13,
    product_code: "CLP-001",
    product_name: "Clipboard",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
  {
    id: 14,
    product_code: "MKR-001",
    product_name: "Marker",
    conversion_factor: 1,
    unit: "PC",
    smallest_unit: "PC",
    is_sales_unit: 1,
  },
];

export { data as mockProductUOM };
