export async function GET(req: Request) {
  const data = [
    {
      id: "614ddacaa468f6c6fb5397bd",
      product_name: "tempor aliqua aliquip amet commodo",
      base_price: 14901132,
      discount_percentage: 42,
      calculated_price: 8642656,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 3,
      material_name: "platinum",
      color_id: 6,
      color_name: "grey",
      description:
        "Non labore et labore mollit dolore in anim ad nostrud. Ea qui ipsum laborum nostrud eiusmod id elit irure pariatur qui et elit adipisicing. Irure elit non veniam ut amet magna et qui fugiat sit eiusmod sunt dolor. Ex ut laboris qui est magna officia et. Labore ut anim ea id reprehenderit excepteur enim ut occaecat qui consectetur voluptate cillum fugiat. Velit in esse culpa nulla laborum elit esse minim eiusmod pariatur mollit ullamco.\r\n",
      rating: 4.1,
    },
    {
      id: "614ddacace77e3d37759ed7a",
      product_name: "Lorem nulla velit dolor laborum",
      base_price: 5553730,
      discount_percentage: 32,
      calculated_price: 3776536,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 1,
      material_name: "silver",
      color_id: 6,
      color_name: "grey",
      description:
        "Non id in labore enim nulla consequat non qui reprehenderit commodo. Non nulla commodo dolor ex laboris adipisicing dolor esse ea consectetur consectetur enim. Ipsum esse et amet mollit culpa consequat est quis enim occaecat nostrud duis est. Do amet commodo culpa commodo. In incididunt in culpa elit.\r\n",
      rating: 2.9,
    },
    {
      id: "614ddacafffaf0d3d70554e8",
      product_name: "incididunt consectetur sunt proident ut",
      base_price: 5783065,
      discount_percentage: 18,
      calculated_price: 4742113,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 1,
      material_name: "silver",
      color_id: 6,
      color_name: "grey",
      description:
        "Amet aliqua proident mollit amet sit exercitation deserunt velit ipsum Lorem irure. Tempor in do et laboris in aliqua mollit dolore officia ea dolore tempor qui culpa. Velit dolor eu deserunt duis ipsum nostrud nisi veniam aute aliqua amet officia minim. Consequat magna ea fugiat non esse mollit. Minim veniam voluptate id est ullamco irure dolor et voluptate.\r\n",
      rating: 4.2,
    },
    {
      id: "614ddaca9c53374e1612aace",
      product_name: "cupidatat consectetur aute et labore",
      base_price: 7015416,
      discount_percentage: 18,
      calculated_price: 5752641,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 4,
      material_name: "titanium",
      color_id: 0,
      color_name: "black",
      description:
        "Officia mollit ipsum sit qui in voluptate enim reprehenderit ut laborum. Laborum aute ut est ad dolore labore est officia amet dolore. Aliqua eu excepteur commodo amet do commodo ea irure qui eiusmod ex proident fugiat esse. Sit elit aliquip ex qui Lorem id. Deserunt ipsum amet eu ullamco aliqua labore nisi cupidatat ea pariatur officia ea ipsum anim.\r\n",
      rating: 4.9,
    },
    {
      id: "614ddaca4456542b91cca45d",
      product_name: "id nostrud aute sunt sint",
      base_price: 15837864,
      discount_percentage: 30,
      calculated_price: 11086504,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 1,
      material_name: "silver",
      color_id: 6,
      color_name: "grey",
      description:
        "Proident mollit ex deserunt aliqua aliqua. Occaecat consectetur ea ut laborum Lorem labore. Amet elit et nisi quis commodo non non in amet. Sit anim Lorem ad incididunt Lorem labore ullamco ea irure laboris qui et laboris eiusmod. Reprehenderit qui magna aute veniam commodo duis consectetur officia dolore consequat anim anim amet.\r\n",
      rating: 1.9,
    },
    {
      id: "614ddaca786c661a915905ec",
      product_name: "occaecat irure eu adipisicing mollit",
      base_price: 14402444,
      discount_percentage: 18,
      calculated_price: 11810004,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 2,
      material_name: "gold",
      color_id: 10,
      color_name: "rose gold",
      description:
        "Fugiat dolor nostrud reprehenderit duis consectetur esse ea veniam do sit in ut sit minim. Veniam ad aliqua nulla anim veniam pariatur tempor nostrud. Qui elit sit reprehenderit sunt proident commodo ullamco ea irure nostrud enim nostrud. Laborum cillum voluptate laborum minim minim nisi aute.\r\n",
      rating: 1.8,
    },
    {
      id: "614ddaca85af100b89588e99",
      product_name: "officia et ipsum sunt sint",
      base_price: 17584751,
      discount_percentage: 33,
      calculated_price: 11781783,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 6,
      material_id: 4,
      material_name: "titanium",
      color_id: 10,
      color_name: "rose gold",
      description:
        "Elit ut duis velit consequat non. Nostrud culpa quis duis esse dolor sunt aute. Sunt exercitation occaecat anim non culpa adipisicing magna ad dolor.\r\n",
      rating: 4.5,
    },
    {
      id: "614ddacadc385b48dde6f415",
      product_name: "cillum ex laboris in anim",
      base_price: 1108251,
      discount_percentage: 9,
      calculated_price: 1008508,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 5,
      material_name: "pearl",
      color_id: 8,
      color_name: "purple",
      description:
        "Quis ut commodo aliquip amet amet incididunt irure cillum dolor commodo do voluptate nulla. Aliqua consectetur id nulla proident nostrud esse sunt minim dolore ullamco. Sit proident nisi et cillum nulla officia velit adipisicing.\r\n",
      rating: 1.3,
    },
    {
      id: "614ddaca8c832f6fce3f9ea9",
      product_name: "sunt veniam et quis ad",
      base_price: 9426817,
      discount_percentage: 32,
      calculated_price: 6410235,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 6,
      material_name: "brass",
      color_id: 4,
      color_name: "gold",
      description:
        "Ipsum magna reprehenderit aute laboris consequat. Sint nulla proident aute est voluptate id. Duis do duis consectetur do magna nisi fugiat cillum est voluptate dolore.\r\n",
      rating: 5,
    },
    {
      id: "614ddacac88ed2950db68d5e",
      product_name: "occaecat nisi mollit laborum in",
      base_price: 2244346,
      discount_percentage: 40,
      calculated_price: 1346607,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 1,
      material_name: "silver",
      color_id: 7,
      color_name: "multi",
      description:
        "Cupidatat mollit esse ut nostrud cillum magna aliquip. Enim nostrud id mollit qui ut velit esse esse excepteur id incididunt adipisicing qui amet. Commodo eu ut occaecat exercitation.\r\n",
      rating: 2.8,
    },
    {
      id: "614ddacac5a4ed869bb4a2ba",
      product_name: "eiusmod sint reprehenderit consectetur amet",
      base_price: 11067872,
      discount_percentage: 35,
      calculated_price: 7194116,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 6,
      material_id: 5,
      material_name: "pearl",
      color_id: 0,
      color_name: "black",
      description:
        "Nulla deserunt mollit exercitation nisi esse cillum do labore ad dolore occaecat. Nulla minim ut proident ad. Culpa cupidatat laborum dolor pariatur laborum laboris fugiat cupidatat mollit consectetur sint aute ad. Mollit magna anim eiusmod laboris elit aliquip voluptate cupidatat minim exercitation pariatur eiusmod dolor consequat. Cupidatat qui ut Lorem ad qui culpa officia.\r\n",
      rating: 1.6,
    },
    {
      id: "614ddacaadeaf5499406720c",
      product_name: "amet ad anim nostrud magna",
      base_price: 9748396,
      discount_percentage: 44,
      calculated_price: 5459101,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 3,
      material_name: "platinum",
      color_id: 1,
      color_name: "blue",
      description:
        "Amet esse est sint ut enim elit aliqua minim irure cupidatat ex labore sint laboris. Quis esse consectetur consequat minim eu tempor id nostrud ipsum ut quis tempor. Voluptate veniam magna qui reprehenderit laboris cillum ex aliquip consectetur reprehenderit. Minim laborum aliquip tempor minim nisi. Ullamco eiusmod id dolore dolor excepteur.\r\n",
      rating: 1.7,
    },
    {
      id: "614ddaca6c4d04f1a2fd133f",
      product_name: "quis proident anim officia consequat",
      base_price: 17712306,
      discount_percentage: 6,
      calculated_price: 16649567,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 5,
      category_name: "Soleil de Artsy",
      material_id: 2,
      material_name: "gold",
      color_id: 1,
      color_name: "blue",
      description:
        "Deserunt nulla cupidatat commodo ea amet enim non elit proident ad minim do. Dolor aliquip consequat ullamco et. Exercitation deserunt aute proident aliquip dolore deserunt do amet sint labore quis anim.\r\n",
      rating: 4.3,
    },
    {
      id: "614ddacacee0bbd0cc01c202",
      product_name: "labore aliquip reprehenderit labore velit",
      base_price: 4659609,
      discount_percentage: 45,
      calculated_price: 2562784,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 5,
      material_name: "pearl",
      color_id: 5,
      color_name: "green",
      description:
        "Sit est excepteur esse culpa occaecat ad adipisicing. Magna aute nostrud laborum eiusmod voluptate nostrud nisi nulla eu non. Aliquip qui deserunt laboris ullamco tempor.\r\n",
      rating: 4.2,
    },
    {
      id: "614ddacaa528b26e2e4527bd",
      product_name: "cillum id eu minim elit",
      base_price: 14092340,
      discount_percentage: 5,
      calculated_price: 13387723,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 5,
      material_name: "pearl",
      color_id: 4,
      color_name: "gold",
      description:
        "Ad nisi elit excepteur amet minim nulla in nisi. Minim qui proident dolor eu enim excepteur in excepteur laboris irure labore exercitation. Incididunt voluptate excepteur aliqua ex ullamco enim excepteur ullamco nostrud velit dolore ea adipisicing esse. Occaecat officia fugiat cupidatat mollit tempor fugiat excepteur amet enim nulla do voluptate enim.\r\n",
      rating: 1.9,
    },
    {
      id: "614ddaca4a065c7a08a9d7b8",
      product_name: "irure commodo ut duis incididunt",
      base_price: 8462272,
      discount_percentage: 5,
      calculated_price: 8039158,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 4,
      material_name: "titanium",
      color_id: 1,
      color_name: "blue",
      description:
        "Non enim ipsum esse irure est irure consequat veniam esse enim officia. Excepteur proident duis reprehenderit excepteur veniam officia. Ipsum cillum irure eiusmod do amet sint proident minim cupidatat culpa cillum. Ad proident deserunt sit laborum eiusmod excepteur cupidatat in ex id. Aliqua occaecat minim occaecat reprehenderit. Dolor mollit ad nulla ut pariatur nisi enim incididunt. Non quis exercitation minim fugiat in do occaecat culpa duis non voluptate commodo aliqua sunt.\r\n",
      rating: 2.8,
    },
    {
      id: "614ddaca6168cafcab6bc0b3",
      product_name: "esse duis non do aliqua",
      base_price: 18768213,
      discount_percentage: 20,
      calculated_price: 15014570,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 3,
      material_name: "platinum",
      color_id: 6,
      color_name: "grey",
      description:
        "Non deserunt ad consequat anim. Cillum anim irure aute ex do non laborum dolore est reprehenderit adipisicing. Aliqua aliqua sunt labore et labore cupidatat nisi id consequat commodo aliquip. Laboris officia cillum non in aliqua ex sit ut. Tempor ut excepteur magna irure dolore eu elit sint elit pariatur eu deserunt anim. Id occaecat voluptate ullamco non.\r\n",
      rating: 1.6,
    },
    {
      id: "614ddaca51a9d24eb5ea966c",
      product_name: "nisi ut proident adipisicing ut",
      base_price: 12996664,
      discount_percentage: 18,
      calculated_price: 10657264,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 6,
      material_id: 6,
      material_name: "brass",
      color_id: 8,
      color_name: "purple",
      description:
        "Nulla ipsum est aute culpa cillum elit ullamco irure. Laborum veniam excepteur ullamco mollit minim esse deserunt irure nisi culpa non laborum eu incididunt. Exercitation esse nisi non ex id enim dolor quis ipsum in Lorem.\r\n",
      rating: 2.8,
    },
    {
      id: "614ddacad2ac17c4aaba8a9b",
      product_name: "Lorem aute nisi proident qui",
      base_price: 14690842,
      discount_percentage: 33,
      calculated_price: 9842864,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 2,
      material_name: "gold",
      color_id: 6,
      color_name: "grey",
      description:
        "Sunt ex nulla sit consectetur. Aliqua id nostrud proident consequat cillum ullamco deserunt eu. Magna veniam proident nisi excepteur exercitation voluptate proident est reprehenderit ex eiusmod sit quis velit. Sunt fugiat proident magna consequat fugiat proident minim occaecat et excepteur occaecat ipsum ad anim. Culpa exercitation ea eu ex pariatur eu enim occaecat nisi esse id. Enim aute nostrud duis ex.\r\n",
      rating: 3.1,
    },
    {
      id: "614ddaca591d722507b4a5bd",
      product_name: "velit non in id cillum",
      base_price: 19317012,
      discount_percentage: 41,
      calculated_price: 11397037,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 1,
      material_name: "silver",
      color_id: 5,
      color_name: "green",
      description:
        "Exercitation id commodo ipsum cillum. Aute ullamco consequat dolor cupidatat duis dolore in non aliqua dolore et. Nulla est ex nostrud quis et.\r\n",
      rating: 4.3,
    },
    {
      id: "614ddaca57c6b3c39fd0ea32",
      product_name: "consectetur quis ullamco in et",
      base_price: 12019343,
      discount_percentage: 32,
      calculated_price: 8173153,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 5,
      category_name: "Soleil de Artsy",
      material_id: 1,
      material_name: "silver",
      color_id: 0,
      color_name: "black",
      description:
        "Id esse ea reprehenderit magna ex laborum tempor Lorem ullamco nulla nostrud. Minim pariatur consectetur enim occaecat ut excepteur voluptate. Aliqua voluptate laboris incididunt reprehenderit incididunt duis magna consectetur culpa voluptate nulla. Sit dolor labore aliquip minim et. Qui nostrud qui eu sint nulla officia amet ipsum.\r\n",
      rating: 4.1,
    },
    {
      id: "614ddacabbe5469bb0d2204c",
      product_name: "eiusmod qui non esse reprehenderit",
      base_price: 15799314,
      discount_percentage: 44,
      calculated_price: 8847615,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 5,
      material_name: "pearl",
      color_id: 0,
      color_name: "black",
      description:
        "Et velit ad labore aliqua consectetur incididunt ullamco officia officia qui. Non culpa ullamco ullamco quis dolor mollit fugiat. Occaecat cupidatat sint dolore officia incididunt dolore non deserunt ex eu veniam nostrud tempor. Dolor sint qui velit incididunt consectetur laboris sit adipisicing cupidatat incididunt sit occaecat culpa.\r\n",
      rating: 4.4,
    },
    {
      id: "614ddaca465635333f776590",
      product_name: "Lorem ad exercitation nostrud elit",
      base_price: 16080869,
      discount_percentage: 16,
      calculated_price: 13507929,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 3,
      material_name: "platinum",
      color_id: 3,
      color_name: "cream",
      description:
        "Nulla ipsum dolore officia aliquip aliquip et ex excepteur velit eu fugiat consectetur velit. Ex ut elit aliqua consequat quis. Ipsum do laborum cupidatat exercitation.\r\n",
      rating: 5,
    },
    {
      id: "614ddacaf030ba05a3b48fc6",
      product_name: "aliquip exercitation eiusmod occaecat in",
      base_price: 4724166,
      discount_percentage: 31,
      calculated_price: 3259674,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 6,
      material_name: "brass",
      color_id: 8,
      color_name: "purple",
      description:
        "Cillum et laborum laboris sint sunt aliquip voluptate occaecat ad labore. Tempor consequat tempor aliquip voluptate aute nostrud. Minim esse labore aliquip ut cupidatat adipisicing reprehenderit consectetur. Officia incididunt mollit laboris id culpa deserunt exercitation minim ea non excepteur ad eiusmod qui.\r\n",
      rating: 5,
    },
    {
      id: "614ddaca7c7e7ccc095a5598",
      product_name: "nisi consequat pariatur qui voluptate",
      base_price: 18433307,
      discount_percentage: 33,
      calculated_price: 12350315,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 2,
      material_name: "gold",
      color_id: 2,
      color_name: "brown",
      description:
        "Do consectetur aliquip excepteur est cupidatat enim proident consectetur proident exercitation. Labore voluptate dolor deserunt et consequat ipsum mollit anim laboris dolore. Esse et anim ex dolore irure ex aliquip labore aliqua sint adipisicing ut irure.\r\n",
      rating: 2,
    },
    {
      id: "614ddaca408a0cd38955f53a",
      product_name: "eu nostrud aliqua dolore sunt",
      base_price: 19428360,
      discount_percentage: 10,
      calculated_price: 17485524,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 3,
      material_name: "platinum",
      color_id: 8,
      color_name: "purple",
      description:
        "Officia minim laboris quis incididunt cillum cillum aliqua nulla. Excepteur labore labore veniam mollit cillum. Minim sunt ex nostrud nostrud. Commodo ullamco velit quis consectetur. Ea anim amet voluptate aute tempor enim quis elit duis occaecat. Aliqua esse do amet irure cillum eu excepteur voluptate sint exercitation sunt. Dolor aute proident consectetur quis mollit anim laborum pariatur anim aliquip aute fugiat laborum.\r\n",
      rating: 3.4,
    },
    {
      id: "614ddaca3e4f490eeb2b5017",
      product_name: "magna ipsum irure excepteur cupidatat",
      base_price: 14639906,
      discount_percentage: 42,
      calculated_price: 8491145,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 2,
      material_name: "gold",
      color_id: 8,
      color_name: "purple",
      description:
        "Et fugiat voluptate voluptate dolore cillum ut do irure ipsum sit. Laborum esse sunt exercitation mollit fugiat est exercitation. Commodo commodo et proident ut.\r\n",
      rating: 2.7,
    },
    {
      id: "614ddacaf2b6f94d13a8fee4",
      product_name: "quis incididunt quis incididunt eu",
      base_price: 10735366,
      discount_percentage: 32,
      calculated_price: 7300048,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 2,
      material_name: "gold",
      color_id: 0,
      color_name: "black",
      description:
        "Cupidatat labore do et nostrud sint reprehenderit sunt irure velit tempor et mollit labore labore. Id tempor do culpa Lorem est est fugiat aliqua ullamco tempor velit anim. Dolor nostrud laborum ad et velit.\r\n",
      rating: 1.6,
    },
    {
      id: "614ddaca182496d4d677e74b",
      product_name: "duis cupidatat ea nisi anim",
      base_price: 9749776,
      discount_percentage: 13,
      calculated_price: 8482305,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 6,
      material_name: "brass",
      color_id: 8,
      color_name: "purple",
      description:
        "Est laboris Lorem id deserunt pariatur non in ex incididunt voluptate commodo dolore. Laboris laborum aliquip pariatur ex nulla laboris cupidatat incididunt laboris aliquip aute labore ipsum ut. Ut incididunt aliqua irure laboris aute.\r\n",
      rating: 3.9,
    },
    {
      id: "614ddaca226f63ccf8f91816",
      product_name: "sunt nisi in exercitation culpa",
      base_price: 4865337,
      discount_percentage: 11,
      calculated_price: 4330149,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 3,
      material_name: "platinum",
      color_id: 8,
      color_name: "purple",
      description:
        "Elit aliqua aliquip pariatur anim minim nulla excepteur in minim amet occaecat culpa elit. Labore eiusmod nulla deserunt minim eu. Labore minim elit ipsum non in eu ut nisi est amet. Exercitation est reprehenderit in adipisicing laborum. Mollit sunt exercitation ea eu labore deserunt incididunt aliquip tempor officia incididunt.\r\n",
      rating: 4.9,
    },
    {
      id: "614ddaca5574f5d35ab7d6f3",
      product_name: "sint id irure laborum aliqua",
      base_price: 2368085,
      discount_percentage: 37,
      calculated_price: 1491893,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 5,
      category_name: "Soleil de Artsy",
      material_id: 1,
      material_name: "silver",
      color_id: 10,
      color_name: "rose gold",
      description:
        "Consectetur sunt non ex excepteur aute culpa amet id proident. Excepteur enim quis proident id aute fugiat ex consequat consectetur. Tempor sint et ullamco aute adipisicing adipisicing amet esse ex dolor duis labore eiusmod adipisicing. Eiusmod laborum consectetur cillum adipisicing nisi consequat dolor labore esse. Qui pariatur magna excepteur excepteur do sit pariatur aliquip cupidatat velit non cillum.\r\n",
      rating: 3.2,
    },
    {
      id: "614ddaca62a666141d2c7731",
      product_name: "eiusmod occaecat commodo sit aute",
      base_price: 11755074,
      discount_percentage: 48,
      calculated_price: 6112638,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 6,
      material_name: "brass",
      color_id: 4,
      color_name: "gold",
      description:
        "Ad dolor aliqua Lorem excepteur ex tempor dolor anim Lorem incididunt sunt eu officia. Proident nisi pariatur cupidatat anim ex sunt fugiat adipisicing magna proident. Aliquip non esse aliquip laborum occaecat magna voluptate amet. Incididunt nostrud labore exercitation dolore sint sint sit duis laborum sint non ad eiusmod ex. Laboris exercitation cillum eu eiusmod exercitation aute consectetur sit exercitation sit duis dolore.\r\n",
      rating: 5,
    },
    {
      id: "614ddaca43b5cd2dab73fdff",
      product_name: "magna qui commodo mollit veniam",
      base_price: 2016467,
      discount_percentage: 11,
      calculated_price: 1794655,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 1,
      material_name: "silver",
      color_id: 5,
      color_name: "green",
      description:
        "Adipisicing deserunt voluptate eiusmod dolore nostrud adipisicing cillum minim ad nulla. Dolore occaecat ipsum dolore deserunt cillum elit. Duis in fugiat ad deserunt veniam non qui amet minim aliqua non quis. Duis elit sit laborum qui quis eiusmod quis non cupidatat. Consequat cupidatat laboris sunt aliqua. Occaecat exercitation culpa proident sit et labore consectetur ad in nulla. Amet minim cupidatat eiusmod ipsum proident.\r\n",
      rating: 4.7,
    },
    {
      id: "614ddaca155ccb22de98945b",
      product_name: "sint deserunt nostrud mollit irure",
      base_price: 1992857,
      discount_percentage: 26,
      calculated_price: 1474714,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 4,
      material_name: "titanium",
      color_id: 7,
      color_name: "multi",
      description:
        "Minim excepteur reprehenderit dolore labore. Aliqua ut do qui in consectetur aliquip nisi labore ex veniam nulla et. Et eiusmod fugiat enim dolor cillum culpa nisi in Lorem proident laborum labore eu.\r\n",
      rating: 4.4,
    },
    {
      id: "614ddacae5c45950246643f8",
      product_name: "anim et elit aliquip reprehenderit",
      base_price: 18285844,
      discount_percentage: 45,
      calculated_price: 10057214,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 3,
      material_name: "platinum",
      color_id: 0,
      color_name: "black",
      description:
        "Ad voluptate veniam dolore quis excepteur aliqua et cillum cupidatat enim labore dolor reprehenderit culpa. Proident ea commodo consectetur commodo sint. Velit enim aute fugiat ex occaecat aliquip dolore ullamco mollit quis sit fugiat. Aliquip incididunt tempor ex laborum voluptate laboris consequat nisi deserunt labore minim ipsum aliquip quis. Esse quis ex aliquip consectetur minim laboris veniam enim aliquip occaecat ex duis ullamco esse. Do et reprehenderit reprehenderit ex in duis ullamco sint ad laborum sit et. Sint pariatur dolore ut in magna aute veniam do deserunt fugiat eiusmod sint occaecat tempor.\r\n",
      rating: 1.8,
    },
    {
      id: "614ddaca84d175f79bfcc816",
      product_name: "proident minim culpa eu pariatur",
      base_price: 13173535,
      discount_percentage: 37,
      calculated_price: 8299327,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 6,
      material_name: "brass",
      color_id: 7,
      color_name: "multi",
      description:
        "Qui est est dolor anim in incididunt in Lorem. Proident aliqua officia consectetur velit. Enim incididunt cillum culpa nostrud nisi aliqua consectetur sit officia aliqua Lorem anim eiusmod. Laboris adipisicing voluptate fugiat elit consequat aliqua minim sit laboris labore.\r\n",
      rating: 3.8,
    },
    {
      id: "614ddaca063eef0179981981",
      product_name: "et et nostrud sint aliquip",
      base_price: 1757872,
      discount_percentage: 20,
      calculated_price: 1406297,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 5,
      material_name: "pearl",
      color_id: 5,
      color_name: "green",
      description:
        "Deserunt deserunt ea mollit nostrud veniam consequat reprehenderit ad non officia reprehenderit magna culpa amet. Consequat veniam incididunt incididunt nulla. Pariatur ea sint ex labore do. Voluptate et anim in in qui. Veniam exercitation deserunt elit ut non culpa velit exercitation amet ad. Cupidatat officia anim do culpa minim culpa nulla ea velit laborum eiusmod aliqua.\r\n",
      rating: 1.5,
    },
    {
      id: "614ddacac14cf1924dd8230d",
      product_name: "ad reprehenderit labore laboris ad",
      base_price: 17137646,
      discount_percentage: 48,
      calculated_price: 8911575,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 6,
      material_name: "brass",
      color_id: 7,
      color_name: "multi",
      description:
        "Exercitation sunt enim cillum deserunt adipisicing aliquip laboris amet aliquip irure eiusmod quis. Velit esse excepteur esse cillum consectetur voluptate dolore consequat duis esse consequat Lorem. Est sit in amet sint dolor eu esse amet aute aliquip ex nulla nisi. Ex fugiat magna excepteur ipsum officia ex eu amet id. Adipisicing occaecat enim amet reprehenderit minim duis consequat deserunt. Elit ex minim ullamco deserunt aliquip ullamco nostrud.\r\n",
      rating: 2.8,
    },
    {
      id: "614ddacaccc0e48ba866150a",
      product_name: "anim commodo nostrud deserunt et",
      base_price: 6063627,
      discount_percentage: 39,
      calculated_price: 3698812,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 2,
      material_name: "gold",
      color_id: 8,
      color_name: "purple",
      description:
        "Ipsum labore sit cupidatat enim eu elit ut sunt. Laborum nulla dolor aute labore magna enim Lorem fugiat qui excepteur ut non ad. Reprehenderit ea fugiat irure aliquip Lorem nulla adipisicing duis cupidatat. Ex veniam aliqua reprehenderit occaecat id sunt eiusmod excepteur fugiat. Ipsum in culpa dolor incididunt occaecat ea mollit veniam fugiat ut cupidatat aute tempor.\r\n",
      rating: 1.2,
    },
    {
      id: "614ddaca534027ec035731e9",
      product_name: "officia reprehenderit in tempor deserunt",
      base_price: 3453846,
      discount_percentage: 36,
      calculated_price: 2210461,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 3,
      category_name: "Ruban",
      material_id: 5,
      material_name: "pearl",
      color_id: 0,
      color_name: "black",
      description:
        "Cillum aliquip incididunt officia velit enim nostrud incididunt labore amet cillum. Nulla excepteur sunt ipsum quis consequat cillum. Ut laboris ex laborum pariatur culpa excepteur laborum commodo. Id magna et non sit Lorem elit laboris laboris proident excepteur laborum dolor.\r\n",
      rating: 3.1,
    },
    {
      id: "614ddacaff1359a89cc26458",
      product_name: "anim nostrud amet proident do",
      base_price: 16353056,
      discount_percentage: 28,
      calculated_price: 11774200,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 5,
      category_name: "Soleil de Artsy",
      material_id: 4,
      material_name: "titanium",
      color_id: 1,
      color_name: "blue",
      description:
        "Excepteur anim ad do et commodo. Quis Lorem quis eu dolore. Ex esse do sint laborum proident est minim aliquip excepteur sunt nisi. Adipisicing irure minim commodo ipsum nostrud voluptate ex ullamco. Culpa duis deserunt velit culpa velit anim. Fugiat duis aute elit veniam eiusmod eiusmod laborum eu amet qui.\r\n",
      rating: 1.2,
    },
    {
      id: "614ddacafbeb4e25024c54af",
      product_name: "consectetur non nulla cupidatat culpa",
      base_price: 10867731,
      discount_percentage: 36,
      calculated_price: 6955347,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 5,
      category_name: "Soleil de Artsy",
      material_id: 4,
      material_name: "titanium",
      color_id: 1,
      color_name: "blue",
      description:
        "Cillum dolor velit laboris minim incididunt consectetur et et nisi ex veniam laboris officia reprehenderit. Reprehenderit fugiat duis fugiat do laborum. Nisi nulla eiusmod adipisicing eu. Ea deserunt anim aute nisi laborum fugiat commodo sint magna proident aute magna. Consectetur nostrud quis elit non adipisicing occaecat laboris ipsum fugiat ea qui ad nulla aliquip.\r\n",
      rating: 2.2,
    },
    {
      id: "614ddaca09e9d4a5f3daceae",
      product_name: "pariatur irure qui tempor aute",
      base_price: 2738697,
      discount_percentage: 13,
      calculated_price: 2382666,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 2,
      material_name: "gold",
      color_id: 1,
      color_name: "blue",
      description:
        "Nostrud sint ipsum sint esse laboris ut velit quis deserunt fugiat occaecat incididunt amet. Minim id Lorem ut ullamco aliquip sunt aliquip dolore adipisicing culpa proident. Esse qui velit deserunt exercitation exercitation amet culpa officia dolore et pariatur tempor est. Sit in irure velit quis velit sint veniam. Officia quis amet quis ex. Adipisicing occaecat commodo tempor enim.\r\n",
      rating: 4.7,
    },
    {
      id: "614ddacae1de1077d9f409c9",
      product_name: "nulla deserunt veniam aute voluptate",
      base_price: 13366356,
      discount_percentage: 28,
      calculated_price: 9623776,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 5,
      material_name: "pearl",
      color_id: 3,
      color_name: "cream",
      description:
        "Sunt amet deserunt officia in. Nulla do ipsum laboris consectetur dolore id id ullamco nostrud. Ipsum proident in anim reprehenderit culpa officia occaecat culpa pariatur nisi quis amet dolor. Anim ea duis et culpa. Magna in proident voluptate mollit amet laboris proident nostrud et nostrud amet adipisicing nostrud Lorem.\r\n",
      rating: 1.7,
    },
    {
      id: "614ddaca937b162687841331",
      product_name: "nulla nulla voluptate enim tempor",
      base_price: 5019562,
      discount_percentage: 42,
      calculated_price: 2911345,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 6,
      material_name: "brass",
      color_id: 4,
      color_name: "gold",
      description:
        "Ipsum ea veniam qui pariatur consectetur ex culpa. Amet qui magna aute sint veniam ut aliqua est ut consequat tempor. Cillum nostrud officia labore sint pariatur consectetur nisi aliqua dolore dolore commodo.\r\n",
      rating: 2.6,
    },
    {
      id: "614ddaca3dee1533bb4ae916",
      product_name: "elit qui veniam fugiat sunt",
      base_price: 15165521,
      discount_percentage: 50,
      calculated_price: 7582760,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 5,
      category_name: "Soleil de Artsy",
      material_id: 3,
      material_name: "platinum",
      color_id: 9,
      color_name: "red",
      description:
        "Cupidatat labore deserunt do velit exercitation do officia quis aliqua aliquip ad excepteur qui. Cupidatat ipsum amet voluptate consequat ad pariatur aliqua consequat non deserunt sunt minim minim. Proident cillum tempor cupidatat exercitation officia veniam aliquip excepteur velit id qui ad. Esse deserunt incididunt ea voluptate ea. Amet aute ad labore fugiat nostrud ullamco qui culpa ut culpa do ut laboris consequat. Ex minim excepteur veniam consectetur velit ea ad ex mollit Lorem pariatur veniam exercitation. Aute culpa veniam aute ex sit.\r\n",
      rating: 2,
    },
    {
      id: "614ddacaf12713f35b03bcea",
      product_name: "cupidatat laborum irure ullamco Lorem",
      base_price: 8989999,
      discount_percentage: 29,
      calculated_price: 6382899,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 1,
      category_name: "Camélia",
      material_id: 1,
      material_name: "silver",
      color_id: 9,
      color_name: "red",
      description:
        "Laborum aute do cupidatat nisi officia eu id anim qui reprehenderit consequat culpa eu nostrud. Minim excepteur consequat enim eu enim et occaecat ex adipisicing minim eiusmod adipisicing. Nostrud esse in ex laborum mollit nulla mollit excepteur duis aute non incididunt minim. Et do eiusmod eu do mollit fugiat veniam nulla id sit minim aliqua nisi. Amet cupidatat mollit non sint eiusmod. Sunt culpa exercitation magna voluptate reprehenderit.\r\n",
      rating: 1.8,
    },
    {
      id: "614ddacade8fe23e82de7729",
      product_name: "adipisicing consectetur incididunt sint incididunt",
      base_price: 19238431,
      discount_percentage: 45,
      calculated_price: 10581137,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 2,
      category_name: "Comète",
      material_id: 4,
      material_name: "titanium",
      color_id: 10,
      color_name: "rose gold",
      description:
        "Reprehenderit exercitation tempor cupidatat Lorem aute pariatur adipisicing cupidatat. Quis tempor Lorem est qui est occaecat. Aute labore excepteur labore consectetur ullamco tempor.\r\n",
      rating: 3.6,
    },
    {
      id: "614ddaca6b049e8b98211ed3",
      product_name: "pariatur reprehenderit exercitation sit nostrud",
      base_price: 5152733,
      discount_percentage: 19,
      calculated_price: 4173713,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 4,
      category_name: "Baroque",
      material_id: 6,
      material_name: "brass",
      color_id: 9,
      color_name: "red",
      description:
        "Lorem aute do adipisicing consectetur non officia ad. Qui ut voluptate cupidatat id id consectetur occaecat id. Est nostrud nostrud adipisicing duis ipsum pariatur ipsum. Eu ad eu cupidatat cillum minim nisi dolore. Lorem est aliquip aliquip nisi ea sint pariatur et do eu nulla incididunt cupidatat. Lorem non esse excepteur mollit sint labore esse in cupidatat dolore laborum fugiat proident Lorem. Dolore est aliqua ullamco mollit non aute ut ullamco ullamco tempor.\r\n",
      rating: 1.8,
    },
    {
      id: "614ddaca62c50d22ff217c33",
      product_name: "ad non enim nisi dolore",
      base_price: 18312799,
      discount_percentage: 32,
      calculated_price: 12452703,
      image: {
        small: "http://placehold.it/32x32",
        medium: "http://placehold.it/32x32",
        large: "http://placehold.it/32x32",
      },
      category_id: 6,
      material_id: 6,
      material_name: "brass",
      color_id: 3,
      color_name: "cream",
      description:
        "Aliqua velit consequat nostrud labore. Laboris qui dolore eu eiusmod aliquip minim ut aute sunt ipsum. Quis reprehenderit dolor amet laboris in consectetur in incididunt et anim. Amet exercitation ad elit dolor anim mollit minim id commodo fugiat magna ipsum veniam deserunt. Commodo anim proident occaecat Lorem ut in aliquip Lorem proident elit.\r\n",
      rating: 4.1,
    },
  ];

  const searchParams = new URLSearchParams(req.url.split("?")[1]);
  const start = searchParams.get("start") ?? `${0}`;
  const limit = searchParams.get("limit") ?? `${data.length}`;
  const numStart = parseInt(start, 10);
  const numLimit = parseInt(limit, 10);

  let resData = [...data];
  resData = resData.slice(numStart, numStart + numLimit);

  return Response.json({
    status: 200,
    count: resData.length,
    data: resData,
  });
}
